active functions: [
  fit_models,
  #  make_plots
]

# =====================================
global filters: &F  # Dict[str, List] # can be None
  reference: [
    Baron,
  ]

# -------------------------------------
fit_models:
  filters: *F
  io:
    - examples/data/04 corrected data
    - examples/info/04 corrected info.xlsx
    - examples/data/12 fitted data ramberg
    - examples/info/12 fitted info.xlsx
  sampling:
    sample_size: 20
  models: [
    #    perfect,
    #    linear,
#        voce,
    ramberg
  ]
  bounds:
    perfect:
      #      E: &E (10e3, 100e3)
      E: &E (0, 100e6)
      s_y: &s_y (30., 100.)
    #      s_y: &s_y (20., 200.)
    linear:
      E: *E
      s_y: *s_y
      H: (0, 1e3)
    voce:
      E: *E
      s_y: *s_y
      s_u: (20., 500.)
      d: (0.1, 50.)
    ramberg:
      E: *E
      s_y: *s_y
      C: (30, 100.)
      q: (0.01, 0.5)
  constraints:
    perfect:
    linear:
    voce:
      A: [ 0, -1, 1, 0 ]
      lb: 10.
      ub: 500.
    ramberg:
# -----------------

# -------------------------------------
make_plots:
  plots:
    - before_after_processing
  before_after_processing:
    filters: *F
    plot_dir: plots
    pdf_name: aakash procb4 aft
    before_dir: data/02 prepared data
    before_info: info/02 prepared info.xlsx
    after_dir: data/03 processed data
    after_info: info/03 processed info.xlsx
# ----------------
