site_name: Paramaterial Documentation
url: https://paramaterial.github.io
site_url: https://dan-slater.github.io/paramaterial/

theme:
  name: material

plugins:
  - mkdocstrings
  - mkdocs-jupyter:
      include_source: True

nav:
  - Home: index.md
  - Example:
      - Data Preparation: example/01 preparation.ipynb
  - Reference:
      - classes.md
      - Functions:
          - preparing.md
          - plotting.md
          - processing.md
          - screening.md
          - modelling.md
