site_name: Paramaterial Documentation
url: https://paramaterial.github.io
site_url: https://dan-slater.github.io/paramaterial/

theme:
  logo: img/pam-icon.png
  favicon: img/pam-icon.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.instant
    - header.autohide
  custom_dir: docs/overrides

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True

nav:
  - Home: index.md
  - Example:
      - Data Preparation: example/01 preparation.ipynb
  - Reference:
      - preparing.md
      - plug.md
      - plotting.md
      - processing.md
      - screening.md
      - modelling.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


