site_name: Paramaterial Documentation
url: https://paramaterial.github.io
site_url: https://dan-slater.github.io/paramaterial/

theme:
  logo: img/pam-icon.png
  favicon: img/pam-icon.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - navigation.top
#    - search.highlight
    - navigation.instant
    - content.code.copy
    - content.code.prettify

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True

nav:
  - Home: index.md
  - Example Notebooks:
      - examples/basic-usage.ipynb
      - examples/dan-msc-cs1.ipynb
      - examples/dan-msc-cs2.ipynb
      - examples/dan-msc-cs3.ipynb
      - examples/dan-msc-cs4.ipynb
  - How-To Guides:
      - guides/prepare-data.md
      - guides/plot-data.md
      - guides/process-data.md
      - guides/screen-data.md
      - guides/aggregate-data.md
      - guides/model-data.md
      - guides/receipts.md
  - Reference:
      - reference/example.md
      - reference/preparing.md
      - reference/plug.md
      - reference/plotting.md
      - reference/processing.md
      - reference/screening.md
      - reference/aggregating.md
      - reference/modelling.md
      - reference/models.md
      - reference/receipts.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


