site_name: Paramaterial Documentation
url: https://paramaterial.github.io
site_url: https://dan-slater.github.io/paramaterial/
theme:
  name: null
  custom_dir: 'cinder'
nav:
  - Home: index.md
  - About: about.md

