site_name: Paramaterial Documentation
url: https://paramaterial.github.io
site_url: https://dan-slater.github.io/paramaterial/

theme:
  logo: img/pam-icon.png
  favicon: img/pam-icon.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    #    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.instant
    - header.autohide
  custom_dir: docs/overrides

plugins:
  - search
  - mkdocstrings
  - mkdocs-jupyter:
      include_source: True
      ignore_h1_titles: True

nav:
  - Home: index.md
  - How-To Guides:
      - how_to_guides/apply_proc_op.md
      - how_to_guides/fit_model.md
      - how_to_guides/make_repr_data.md
      - how_to_guides/use_screening_pdf.md
      - how_to_guides/zener_holloman_eg.ipynb
  - Example:
      - Basic Usage: example/paramaterial-basic-usage.ipynb
  - Reference:
      - reference/aggregate.md
      - reference/example.md
      - reference/models.md
      - reference/plotting.md
      - reference/plug.md
      - reference/prep.md
      - reference/proc_ops.md
      - reference/receipts.md
      - reference/screening.md

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js


